### ISSUE TITLE
Document parse failure

### ISSUE THREAD

**Issue by samuelcouch** [jpf/TwilioSheet#1]
Twilio doesn't seem to like the formatting of the response. 

> Error on line 1 of document : Content is not allowed in prolog. Please ensure that the response body is a valid XML document.

and the body of the response it records is `itted successfully!` (not sure where the "Subm" portion disappears...)

Going to try and resolve this, but figured it was worth posting.

**Comment by jpf** [comment]
Oh, interesting. Did you figure out how to solve this?

**Comment by samuelcouch** [comment]
I didn't figure it out. I took a look at the [error reference](http://www.twilio.com/docs/errors/12100) which suggested that the response needed to be valid XML which rooted with the `<Response>` element. I tried adding it to the return response in `gform.submit()` but it didn't solve the problem.

Haven't had much time to actual look into it, but I am curious about it. Do you have any ideas?

**Comment by samuelcouch** [comment]
I haven't had a chance to test it, but could the fix be using `twiml.Response()` to post the message? 

``` python
from twilio import twiml

message = twiml.Response()
message.say("Submitted successfully!")
```

I'm really just trying to figure out the ins and outs of using Twilio, but from [the documentation](http://www.twilio.com/docs/quickstart/python/twiml/say-response) it seems that this would satisfy needing XML responses. It's possible that I'm understanding it incorrectly though.

**Comment by jpf** [comment]
Bingo. That was it. Thanks for the inspiration to fix this. Here's what I did: https://github.com/jpf/TwilioSheet/commit/d820fdbb45fc52c43285816a5b52b51d927593c4

**Comment by samuelcouch** [comment]
Oh excellent. Glad I could be of some help.
